"""Initial-Migration der Asset-Engine.

Erzeugt AssetPack, GeneratedAsset, AssetGenerationJob und AssetLibraryItem.
"""

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0006_smartboard_pipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('grade', models.CharField(blank=True, max_length=60)),
                ('topic', models.CharField(blank=True, max_length=220)),
                ('style_family', models.CharField(blank=True, max_length=120)),
                ('style_dna', models.JSONField(blank=True, default=dict)),
                ('design_tokens', models.JSONField(blank=True, default=dict)),
                ('palette', models.JSONField(blank=True, default=dict)),
                ('asset_plan', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(
                    choices=[
                        ('planned', 'Geplant'),
                        ('generating', 'In Erzeugung'),
                        ('ready', 'Bereit'),
                        ('partially_failed', 'Teilweise fehlgeschlagen'),
                        ('failed', 'Fehlgeschlagen'),
                        ('archived', 'Archiviert'),
                    ],
                    default='planned',
                    max_length=30,
                )),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('consistency_report', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='asset_packs',
                    to='boards.board',
                )),
                ('owner', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='asset_packs',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_asset_packs',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(
                    choices=[
                        ('mascot', 'Mascot'),
                        ('character', 'Charakter'),
                        ('animal', 'Tier'),
                        ('icon', 'Icon'),
                        ('scene_object', 'Szenenobjekt'),
                        ('background_layer', 'Hintergrund'),
                        ('decorative', 'Dekoration'),
                        ('frame', 'Rahmen'),
                        ('badge', 'Badge'),
                        ('sticker', 'Sticker'),
                        ('marker', 'Marker'),
                        ('arrow', 'Pfeil'),
                        ('diagram_symbol', 'Diagramm-Symbol'),
                        ('pattern', 'Muster'),
                        ('overlay', 'Overlay'),
                        ('card_skin', 'Kartenstil'),
                        ('other', 'Sonstiges'),
                    ],
                    default='other',
                    max_length=40,
                )),
                ('subject_text', models.CharField(blank=True, max_length=255)),
                ('style_family', models.CharField(blank=True, max_length=120)),
                ('strategy', models.CharField(
                    choices=[
                        ('compiler', 'Compiler (Mascot/Shape Kit)'),
                        ('procedural', 'Prozedural'),
                        ('template_remix', 'Template-Remix'),
                        ('svg_free_draw', 'SVG Free Draw'),
                        ('asset_library', 'Asset-Bibliothek'),
                        ('fallback_simple', 'Fallback (einfach)'),
                    ],
                    default='svg_free_draw',
                    max_length=40,
                )),
                ('priority', models.CharField(
                    choices=[
                        ('low', 'Niedrig'),
                        ('medium', 'Mittel'),
                        ('high', 'Hoch'),
                        ('hero', 'Hero'),
                    ],
                    default='medium',
                    max_length=20,
                )),
                ('background_mode', models.CharField(
                    choices=[
                        ('transparent_cutout', 'Freigestellt (transparent)'),
                        ('framed_scene', 'Eingerahmte Szene'),
                        ('full_background', 'Voller Hintergrund'),
                        ('overlay_frame', 'Overlay-Rahmen'),
                        ('partial_overlay', 'Teil-Overlay'),
                    ],
                    default='transparent_cutout',
                    max_length=30,
                )),
                ('asset_spec', models.JSONField(blank=True, default=dict)),
                ('svg', models.TextField(blank=True)),
                ('normalized_svg', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_assets/')),
                ('preview_png', models.FileField(blank=True, null=True, upload_to='generated_assets/previews/')),
                ('width', models.PositiveIntegerField(default=512)),
                ('height', models.PositiveIntegerField(default=512)),
                ('viewbox', models.CharField(blank=True, max_length=120)),
                ('generation_prompt', models.TextField(blank=True)),
                ('ai_raw_output', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('quality_report', models.JSONField(blank=True, default=dict)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('repair_history', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_reusable', models.BooleanField(default=False)),
                ('is_quality_example', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_pack', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='assets',
                    to='assets.assetpack',
                )),
                ('board', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='generated_assets',
                    to='boards.board',
                )),
                ('owner', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='generated_assets',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('created_by', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_generated_assets',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='generatedasset',
            constraint=models.UniqueConstraint(
                condition=models.Q(('asset_pack__isnull', False)),
                fields=('asset_pack', 'key'),
                name='generated_asset_pack_key_uniq',
            ),
        ),
        migrations.CreateModel(
            name='AssetGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_key', models.SlugField(max_length=80)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Wartend'),
                        ('running', 'Läuft'),
                        ('completed', 'Abgeschlossen'),
                        ('failed', 'Fehlgeschlagen'),
                        ('repaired', 'Repariert'),
                        ('skipped', 'Übersprungen'),
                    ],
                    default='pending',
                    max_length=30,
                )),
                ('request', models.JSONField(blank=True, default=dict)),
                ('selected_strategy', models.CharField(blank=True, max_length=40)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_pack', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='jobs',
                    to='assets.assetpack',
                )),
                ('result_asset', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='jobs',
                    to='assets.generatedasset',
                )),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='AssetLibraryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('asset_type', models.CharField(
                    choices=[
                        ('mascot', 'Mascot'),
                        ('character', 'Charakter'),
                        ('animal', 'Tier'),
                        ('icon', 'Icon'),
                        ('scene_object', 'Szenenobjekt'),
                        ('background_layer', 'Hintergrund'),
                        ('decorative', 'Dekoration'),
                        ('frame', 'Rahmen'),
                        ('badge', 'Badge'),
                        ('sticker', 'Sticker'),
                        ('marker', 'Marker'),
                        ('arrow', 'Pfeil'),
                        ('diagram_symbol', 'Diagramm-Symbol'),
                        ('pattern', 'Muster'),
                        ('overlay', 'Overlay'),
                        ('card_skin', 'Kartenstil'),
                        ('other', 'Sonstiges'),
                    ],
                    default='other',
                    max_length=40,
                )),
                ('style_family', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('svg', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='asset_library/')),
                ('license', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['title']},
        ),
    ]
