# Generated by Django 5.2.13 on 2026-05-04 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('source_format', models.CharField(choices=[('yaml', 'YAML'), ('json', 'JSON')], default='yaml', max_length=10)),
                ('blueprint', models.JSONField(default=dict)),
                ('preview_svg', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=40)),
                ('is_system', models.BooleanField(default=False)),
                ('quality_score', models.FloatField(default=0)),
                ('last_validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
