# Generated by Django 5.2.13 on 2026-05-05 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=180)),
                ('subject', models.CharField(max_length=120)),
                ('grade_band', models.CharField(blank=True, max_length=60)),
                ('topic_area', models.CharField(blank=True, max_length=220)),
                ('rule_type', models.CharField(choices=[('arithmetic_range', 'Zahlenraum'), ('operation_type', 'Operationstyp'), ('task_count', 'Aufgabenanzahl'), ('solution_check', 'Lösungsprüfung'), ('text_length', 'Textlänge'), ('allowed_operators', 'Operatoren'), ('custom', 'Benutzerdefiniert')], default='custom', max_length=40)),
                ('config', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(default='DE', max_length=80)),
                ('document_type', models.CharField(choices=[('teil_a', 'Teil A'), ('teil_b', 'Teil B'), ('teil_c_subject', 'Teil C / Fach'), ('rlp_kompakt', 'RLP kompakt'), ('other', 'Sonstiges')], default='other', max_length=32)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='curriculum_sources/')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extracted_pages', models.JSONField(default=list)),
                ('extraction_status', models.CharField(choices=[('not_extracted', 'Nicht extrahiert'), ('extracting', 'Extrahiert …'), ('extracted', 'Extrahiert'), ('failed', 'Fehlgeschlagen')], default='not_extracted', max_length=20)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_images_generated', models.BooleanField(default=False)),
                ('page_preview_paths', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_sources_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('grade_band', models.CharField(max_length=60)),
                ('level_band', models.JSONField(default=list)),
                ('topic_hint', models.CharField(blank=True, max_length=220)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_pages', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending', 'Ausstehend'), ('running', 'Läuft'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('approved', 'Genehmigt')], default='draft', max_length=20)),
                ('prompt_text', models.TextField(blank=True)),
                ('ai_raw_output', models.JSONField(default=dict)),
                ('extracted_context', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('review_status', models.CharField(choices=[('not_reviewed', 'Nicht geprüft'), ('needs_review', 'Prüfung nötig'), ('reviewed', 'Geprüft'), ('rejected', 'Abgelehnt')], default='not_reviewed', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_excerpt', models.JSONField(default=dict)),
                ('extraction_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_extraction_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_curriculum_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='curricula.curriculumsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=120)),
                ('country', models.CharField(default='DE', max_length=80)),
                ('curriculum_version', models.CharField(blank=True, max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('grade_band', models.CharField(max_length=60)),
                ('level_band', models.JSONField(default=list)),
                ('topic_area', models.CharField(max_length=220)),
                ('subtopics', models.JSONField(default=list)),
                ('competency_goals', models.JSONField(default=list)),
                ('knowledge_goals', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('allowed_task_types', models.JSONField(default=list)),
                ('recommended_worksheet_formats', models.JSONField(default=list)),
                ('language_guidance', models.JSONField(default=dict)),
                ('media_guidance', models.JSONField(default=list)),
                ('cross_curricular_links', models.JSONField(default=list)),
                ('validation_rules', models.JSONField(default=list)),
                ('difficulty_notes', models.JSONField(default=list)),
                ('source_refs', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('quality_status', models.CharField(choices=[('unchecked', 'Ungeprüft'), ('ai_extracted', 'KI-extrahiert'), ('human_reviewed', 'Manuell geprüft')], default='unchecked', max_length=20)),
                ('public_summary', models.TextField(blank=True)),
                ('teacher_facing_summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_contexts_created', to=settings.AUTH_USER_MODEL)),
                ('extraction_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexts_created', to='curricula.curriculumextractionjob')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexts', to='curricula.curriculumsource')),
            ],
            options={
                'ordering': ['state', 'subject', 'grade_band', 'topic_area'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetCurriculumUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('match_reasons', models.JSONField(default=list)),
                ('used_context_snapshot', models.JSONField(default=dict)),
                ('teacher_visible_summary', models.JSONField(default=dict)),
                ('ai_usage_note', models.TextField(blank=True)),
                ('curriculum_alignment', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_usages', to='curricula.curriculumcontext')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_usages', to='worksheets.worksheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
