# Generated by Django 5.2.13 on 2026-05-05 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=120)),
                ('grade', models.CharField(blank=True, max_length=60)),
                ('topic', models.CharField(blank=True, max_length=220)),
                ('board_type', models.CharField(choices=[('interactive_board', 'Interaktives Board'), ('lesson_intro', 'Stundeneinstieg'), ('practice_board', 'Übungstafel'), ('explanation_board', 'Erklärtafel'), ('quiz_board', 'Quiz-Tafel')], default='interactive_board', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('generated', 'Erzeugt'), ('archived', 'Archiviert')], default='draft', max_length=20)),
                ('spec', models.JSONField(default=dict)),
                ('generation_prompt', models.TextField(blank=True)),
                ('generation_input', models.JSONField(default=dict)),
                ('ai_raw_output', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('previous_spec', models.JSONField(default=dict)),
                ('new_spec', models.JSONField(default=dict)),
                ('ai_raw_output', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='boards.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
