# Generated by Django 5.2.13 on 2026-05-05 10:39

import apps.boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='free_html',
            field=models.JSONField(default=apps.boards.models.default_free_html_payload),
        ),
        migrations.AddField(
            model_name='board',
            name='generation_mode',
            field=models.CharField(choices=[('structured', 'Strukturiert (BoardSpec)'), ('free_html', 'Freies HTML5 (experimentell)')], default='structured', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='sandbox_options',
            field=models.JSONField(default=apps.boards.models.default_sandbox_options),
        ),
        migrations.AddField(
            model_name='boardrevision',
            name='generation_mode',
            field=models.CharField(choices=[('structured', 'Strukturiert (BoardSpec)'), ('free_html', 'Freies HTML5 (experimentell)')], default='structured', max_length=20),
        ),
        migrations.AddField(
            model_name='boardrevision',
            name='new_free_html',
            field=models.JSONField(default=apps.boards.models.default_free_html_payload),
        ),
        migrations.AddField(
            model_name='boardrevision',
            name='previous_free_html',
            field=models.JSONField(default=apps.boards.models.default_free_html_payload),
        ),
    ]
