# Generated by Django 5.2.13 on 2026-05-07 09:48

from django.db import migrations, models


def forwards_board_moderation(apps, schema_editor):
    Board = apps.get_model('boards', 'Board')
    Board.objects.filter(library_public=True).update(library_moderation_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_board_library_listing_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='boards_aius_step_ty_852247_idx',
            old_name='boards_aius_step_ty_a8c6f3_idx',
        ),
        migrations.RenameIndex(
            model_name='aiusagelog',
            new_name='boards_aius_board_i_ef28c4_idx',
            old_name='boards_aius_board_i_5e8b22_idx',
        ),
        migrations.RenameIndex(
            model_name='boardlibrarycomment',
            new_name='boards_boar_board_i_c0e2ab_idx',
            old_name='boards_boar_board_i_idx',
        ),
        migrations.AddField(
            model_name='board',
            name='library_moderation_status',
            field=models.CharField(choices=[('none', 'Nicht eingereicht'), ('pending', 'Freigabe ausstehend'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], db_index=True, default='none', max_length=20),
        ),
        migrations.RunPython(forwards_board_moderation, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aiusagelog',
            name='step_type',
            field=models.CharField(choices=[('intent', 'Intent'), ('risk', 'Risk'), ('creative_brief', 'Creative Brief'), ('style_dna', 'Style DNA'), ('code_generation', 'Code-Generierung'), ('repair', 'Reparatur'), ('screenshot_judge', 'Screenshot-Judge'), ('revision', 'Revision'), ('asset_intent', 'Asset Intent'), ('asset_plan', 'Asset Plan'), ('asset_strategy', 'Asset Strategy'), ('asset_svg_generation', 'Asset SVG Generation'), ('asset_repair', 'Asset Repair'), ('asset_quality_judge', 'Asset Quality Judge'), ('asset_pack_consistency', 'Asset Pack Consistency'), ('asset_pack_generation', 'Asset Pack Generation'), ('worksheet_generation', 'Arbeitsblatt Generierung'), ('worksheet_review', 'Arbeitsblatt Review'), ('worksheet_page_regenerate', 'Arbeitsblatt Seite regenerieren'), ('blocks_slot_fill', 'Bausteine Slot-Filling'), ('curriculum_extraction', 'Lehrplan-KI-Extraktion'), ('curriculum_auto_discovery', 'Lehrplan Auto-Discovery')], max_length=40),
        ),
    ]
