# Generated by Django 5.2.13 on 2026-05-07 10:02

from django.db import migrations, models


def forwards_grade_bounds(apps, schema_editor):
    Board = apps.get_model('boards', 'Board')
    from apps.boards.grade_bounds import infer_bounds_from_grade_text

    for b in Board.objects.exclude(grade='').iterator():
        if b.grade_from is not None and b.grade_to is not None:
            continue
        lo, hi = infer_bounds_from_grade_text(str(b.grade or ''))
        if lo is not None and hi is not None:
            Board.objects.filter(pk=b.pk).update(grade_from=lo, grade_to=hi)


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_library_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='grade_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='grade_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_grade_bounds, migrations.RunPython.noop),
    ]
