# Generated by Django 5.2.13 on 2026-05-07

from django.db import migrations, models


def forwards_fill_classification_snapshot(apps, schema_editor):
    Board = apps.get_model('boards', 'Board')

    def dur(b):
        gi = b.generation_input if isinstance(b.generation_input, dict) else {}
        raw = gi.get('duration_minutes')
        if raw is None:
            return None
        try:
            v = int(raw)
            return v if v > 0 else None
        except (TypeError, ValueError):
            return None

    for b in Board.objects.exclude(library_snapshot_at__isnull=True).iterator():
        Board.objects.filter(pk=b.pk).update(
            library_snapshot_subject=b.subject or '',
            library_snapshot_grade=b.grade or '',
            library_snapshot_grade_from=b.grade_from,
            library_snapshot_grade_to=b.grade_to,
            library_snapshot_duration_minutes=dur(b),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_board_grade_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='library_snapshot_subject',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='board',
            name='library_snapshot_grade',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='board',
            name='library_snapshot_grade_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='library_snapshot_grade_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='library_snapshot_duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_fill_classification_snapshot, migrations.RunPython.noop),
    ]
