from django.core.management.base import BaseCommand
from apps.patterns.models import WorksheetPattern

def preview(title, color='#6366f1'):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="240" height="340" viewBox="0 0 240 340"><rect width="240" height="340" fill="white"/><rect x="18" y="18" width="204" height="56" rx="12" fill="{color}" opacity=".16"/><text x="28" y="52" font-size="16" font-family="Arial" font-weight="700" fill="#111827">{title}</text><rect x="24" y="94" width="88" height="70" rx="10" fill="#f8fafc" stroke="#cbd5e1"/><rect x="128" y="94" width="88" height="70" rx="10" fill="#f8fafc" stroke="#cbd5e1"/><rect x="24" y="182" width="192" height="82" rx="10" fill="#fff7ed" stroke="#fdba74"/><line x1="42" y1="214" x2="198" y2="214" stroke="#9ca3af"/><line x1="42" y1="238" x2="198" y2="238" stroke="#9ca3af"/></svg>'''

PATTERNS=[
{
'id':'primary_math_addition_big_boxes_v1','name':'Addition bis 20 – große Kästchen','description':'Grundschul-Rechenblatt mit großen Antwortboxen.','metadata':{'subjects':['Mathematik'],'grades':[1,2],'school_types':['Grundschule'],'difficulty':['easy','medium'],'suitable_topics':['Addition bis 20','Plusaufgaben','Kopfrechnen']},'generation_rules':{'operation':'addition','min_result':0,'max_result':20,'min_tasks':12,'max_tasks':18,'require_solutions':True,'forbidden_operations':['subtraction','multiplication','division']},'layout':{'template_id':'primary_big_number_grid_v1','renderer':'html','page_format':'A4','orientation':'portrait','visual_density':'low','answer_area_scale':'extra_large'},'slots':[{'key':'title','type':'text','required':True,'max_length':80},{'key':'tasks','type':'arithmetic_task_list','required':True,'min_items':12,'max_items':18,'constraints':{'operation':'addition','max_result':20}},{'key':'bonus_task','type':'task','required':False},{'key':'solutions','type':'solution_list','required':True}], 'design':{'creativity_supported':['classic','balanced','highly_creative'],'default_creativity':'balanced','allowed_themes':['monster','space','forest','neutral']}, 'validation':{'validators':['arithmetic_addition_max_result','task_count_range','solutions_match_tasks']}, 'preview_svg':preview('Plus bis 20','#22c55e')},
{
'id':'reading_comprehension_v1','name':'Lesetext mit Verständnisfragen','description':'Kurzer Text, Fragen, Schreiblinien.','metadata':{'subjects':['Deutsch','Englisch','Französisch'],'grades':[2,3,4,5,6],'school_types':['Grundschule','Gymnasium','Gesamtschule'],'difficulty':['easy','medium'],'suitable_topics':['Lesen','Sachtext','Textverständnis']},'generation_rules':{'min_tasks':5,'max_tasks':8,'require_solutions':True},'layout':{'template_id':'reading_comprehension_v1','renderer':'html','page_format':'A4','orientation':'portrait'},'slots':[{'key':'title','type':'text','required':True},{'key':'reading_text','type':'rich_text','required':True,'max_length':1400},{'key':'questions','type':'task_list','required':True,'min_items':5,'max_items':8},{'key':'solutions','type':'solution_list','required':True}], 'design':{'creativity_supported':['classic','balanced'],'default_creativity':'classic'}, 'validation':{'validators':['required_slots_filled','solutions_present']}, 'preview_svg':preview('Lesen & Fragen','#3b82f6')},
{
'id':'checklist_research_sheet_v1','name':'Forscherbogen / Checkliste','description':'Sachkunde, Naturwissenschaften, Projektarbeit.','metadata':{'subjects':['Sachkunde','Biologie','Physik','Chemie','Geschichte','Politik'],'grades':[3,4,5,6,7,8],'school_types':['Grundschule','Gymnasium','Gesamtschule'],'difficulty':['easy','medium'],'suitable_topics':['Forscherbogen','Experiment','Recherche','Beobachtung']},'generation_rules':{'min_tasks':4,'max_tasks':8,'require_solutions':False},'layout':{'template_id':'checklist_research_v1','renderer':'html','page_format':'A4','orientation':'portrait'},'slots':[{'key':'title','type':'text','required':True},{'key':'intro_text','type':'text','required':False},{'key':'checklist','type':'checklist','required':True,'min_items':5,'max_items':12},{'key':'observation_table','type':'table','required':False},{'key':'drawing_box','type':'drawing_box','required':False}], 'design':{'creativity_supported':['balanced','highly_creative'],'default_creativity':'balanced'}, 'validation':{'validators':['required_slots_filled']}, 'preview_svg':preview('Forscherbogen','#f59e0b')},
{
'id':'academic_problem_set_v1','name':'Akademisches Aufgabenblatt','description':'Sachliches Blatt für Oberstufe und Uni.','metadata':{'subjects':['Mathematik','Physik','Chemie','Informatik','Biologie','Wirtschaft','Jura'],'grades':[10,11,12,13],'school_types':['Gymnasium','Uni'],'difficulty':['medium','hard'],'suitable_topics':['Übungsblatt','Problemset','Klausurtraining']},'generation_rules':{'min_tasks':4,'max_tasks':10,'require_solutions':True},'layout':{'template_id':'academic_problem_set_v1','renderer':'html','page_format':'A4','orientation':'portrait'},'slots':[{'key':'title','type':'text','required':True},{'key':'theory_box','type':'rich_text','required':False},{'key':'tasks','type':'task_list','required':True,'min_items':4,'max_items':10},{'key':'solutions','type':'solution_list','required':True},{'key':'rubric','type':'rubric','required':False}], 'design':{'creativity_supported':['classic'],'default_creativity':'classic'}, 'validation':{'validators':['required_slots_filled','solutions_present']}, 'preview_svg':preview('Problemset','#64748b')}
]
class Command(BaseCommand):
    def handle(self,*args,**kwargs):
        for bp in PATTERNS:
            WorksheetPattern.objects.update_or_create(key=bp['id'], defaults={'name':bp['name'],'description':bp.get('description',''),'status':'active','source_format':'json','blueprint':bp,'preview_svg':bp.get('preview_svg',''),'is_system':True,'quality_score':9})
        self.stdout.write(self.style.SUCCESS(f'Seeded {len(PATTERNS)} patterns.'))
