# Generated by Django 5.2.13 on 2026-05-06 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_credit_accounts(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserCreditBalance = apps.get_model('accounts', 'UserCreditBalance')
    initial = 10000
    for uid in User.objects.values_list('id', flat=True):
        UserCreditBalance.objects.get_or_create(user_id=uid, defaults={'balance': initial})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit-Konto',
                'verbose_name_plural': 'Credit-Konten',
            },
        ),
        migrations.RunPython(forwards_credit_accounts, noop_reverse),
    ]
