# Generated by Django 5.2.13 on 2026-05-10 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_plans_and_subscriptions(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    UserSubscription = apps.get_model('accounts', 'UserSubscription')
    UserCreditBalance = apps.get_model('accounts', 'UserCreditBalance')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    plan_defs = (
        ('free', 'Kostenlos', 0, 0),
        ('pro', 'Pro', 50_000, 1),
        ('team', 'Team', 200_000, 2),
    )
    for slug, name, grant, order in plan_defs:
        SubscriptionPlan.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'monthly_credit_grant': grant,
                'sort_order': order,
                'is_active': True,
            },
        )

    free = SubscriptionPlan.objects.get(slug='free')
    for uid in User.objects.values_list('id', flat=True):
        UserSubscription.objects.get_or_create(
            user_id=uid,
            defaults={'plan_id': free.pk, 'status': 'active'},
        )

    for sub in UserSubscription.objects.filter(plan_id=free.pk):
        user = User.objects.filter(pk=sub.user_id).first()
        if not user or getattr(user, 'is_staff', False):
            continue
        UserCreditBalance.objects.filter(user_id=user.pk).update(balance=0)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_user_credit_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('monthly_credit_grant', models.PositiveIntegerField(default=0, help_text='Credits, die pro Abrechnungsperiode gutgeschrieben werden (Free = 0).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Optional: Stripe Price ID bei Integration.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abo-Plan',
                'verbose_name_plural': 'Abo-Pläne',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='usercreditbalance',
            name='last_monthly_grant_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercreditbalance',
            name='last_monthly_grant_key',
            field=models.CharField(blank=True, help_text='Idempotenz für periodische Gutschriften (z. B. YYYY-MM oder Stripe invoice id).', max_length=32),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('canceled', 'Gekündigt'), ('past_due', 'Zahlung ausstehend'), ('trialing', 'Testphase')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzer-Abo',
                'verbose_name_plural': 'Nutzer-Abos',
            },
        ),
        migrations.RunPython(seed_plans_and_subscriptions, noop_reverse),
    ]
