# Generated by Django 5.2

from django.db import migrations, models


def migrate_plans_and_reset_subscriptions(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    UserSubscription = apps.get_model('accounts', 'UserSubscription')
    free = SubscriptionPlan.objects.get(slug='free')
    SubscriptionPlan.objects.filter(slug__in=('pro', 'team')).update(is_active=False)
    SubscriptionPlan.objects.update_or_create(
        slug='starter_10',
        defaults={
            'name': 'Starter — 10 €/Monat',
            'monthly_credit_grant': 5000,
            'sort_order': 1,
            'is_active': True,
            'stripe_price_id': '',
        },
    )
    SubscriptionPlan.objects.update_or_create(
        slug='pro_20',
        defaults={
            'name': 'Pro — 20 €/Monat',
            'monthly_credit_grant': 10000,
            'sort_order': 2,
            'is_active': True,
            'stripe_price_id': '',
        },
    )
    UserSubscription.objects.exclude(plan_id=free.pk).update(
        plan_id=free.pk,
        status='active',
        stripe_customer_id='',
        stripe_subscription_id='',
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscription_plans_and_grants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditbalance',
            name='last_monthly_grant_key',
            field=models.CharField(
                blank=True,
                help_text='Idempotenz für periodische Gutschriften (z. B. YYYY-MM oder Stripe invoice id).',
                max_length=64,
            ),
        ),
        migrations.RunPython(migrate_plans_and_reset_subscriptions, noop_reverse),
    ]
