# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Credit-Paket-Definitionen — Basis: 10k Credits ≙ 10 € + 30 % Marge ⇒ 13 €.
# Bei größeren Paketen progressiver Mengenrabatt (Upsell-Anreiz).
CREDIT_PACKAGES_SEED: tuple[tuple[str, str, int, int, str, bool, int], ...] = (
    # (slug, name, credits, price_cents, badge, highlighted, sort_order)
    ('pack_1k', 'Mini', 1_000, 149, '', False, 1),
    ('pack_5k', 'Standard', 5_000, 649, '', False, 2),
    ('pack_10k', 'Plus', 10_000, 1_299, 'Beliebteste', True, 3),
    ('pack_25k', 'Power', 25_000, 2_999, 'Bester Preis', False, 4),
    ('pack_50k', 'Profi', 50_000, 5_499, '-15 %', False, 5),
)


def seed_basic_plan_and_credit_packages(apps, schema_editor):
    SubscriptionPlan = apps.get_model('accounts', 'SubscriptionPlan')
    CreditPackage = apps.get_model('accounts', 'CreditPackage')

    SubscriptionPlan.objects.update_or_create(
        slug='basic_5',
        defaults={
            'name': 'Basic — 5 €/Monat',
            'monthly_credit_grant': 2500,
            'sort_order': 0,
            'is_active': True,
            'stripe_price_id': '',
        },
    )

    for slug, name, credits, price_cents, badge, highlighted, sort_order in CREDIT_PACKAGES_SEED:
        CreditPackage.objects.update_or_create(
            slug=slug,
            defaults={
                'name': name,
                'credits': credits,
                'price_cents': price_cents,
                'currency': 'eur',
                'badge_label': badge,
                'highlighted': highlighted,
                'is_active': True,
                'sort_order': sort_order,
                'stripe_price_id': '',
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stripe_plans_and_grant_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('credits', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField(help_text='Bruttopreis in Cent (z. B. 1299 = 12,99 €).')),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('badge_label', models.CharField(blank=True, help_text='Optionales Label für die UI (z. B. "Beliebteste", "Bester Preis").', max_length=32)),
                ('highlighted', models.BooleanField(default=False, help_text='Visuelle Hervorhebung (gehighlighte Karte in der UI).')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Optional: Stripe Price ID. Leer ⇒ Checkout nutzt price_data dynamisch.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit-Paket',
                'verbose_name_plural': 'Credit-Pakete',
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('credits', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Offen'), ('paid', 'Bezahlt'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounts.creditpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit-Kauf',
                'verbose_name_plural': 'Credit-Käufe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_basic_plan_and_credit_packages, noop_reverse),
    ]
