# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for row in User.objects.all().only('pk').iterator():
        UserProfile.objects.get_or_create(user_id=row.pk, defaults={'is_demo': False})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_basic_plan_and_credit_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'is_demo',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='True: Demo-Zugang über Credit-Saldo, keine Zahlungen/Monatsgrants.',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Nutzerprofil',
                'verbose_name_plural': 'Nutzerprofile',
            },
        ),
        migrations.RunPython(backfill_user_profiles, migrations.RunPython.noop),
    ]
