import { Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { api } from './lib/api';
import { GeneratorPage } from './features/generator/GeneratorPage';
import { WorksheetPage } from './features/worksheets/WorksheetPage';
import { MyWorksheetsPage } from './features/worksheets/MyWorksheetsPage';
import { PatternPage } from './features/settings/PatternPage';

function Login(){const nav=useNavigate();const [email,setEmail]=useState('demo@example.com');const [password,setPassword]=useState('DemoPass123!');const [err,setErr]=useState('');async function login(){try{const r=await api.post('/auth/login/',{username:email,password});localStorage.setItem('access',r.data.access);localStorage.setItem('refresh',r.data.refresh);nav('/app');}catch(e:any){setErr('Login fehlgeschlagen. Registriere dich zuerst.')}}async function register(){try{await api.post('/auth/register/',{email,password,first_name:'Demo',last_name:'Teacher'});await login();}catch(e:any){setErr(JSON.stringify(e.response?.data || e.message));}}return <div className="min-h-screen grid place-items-center"><div className="bg-white p-8 rounded-2xl shadow w-[380px]"><h1 className="text-2xl font-bold mb-4">WorksheetAI HTML A4 MVP</h1><input className="border p-2 w-full mb-2" value={email} onChange={e=>setEmail(e.target.value)}/><input className="border p-2 w-full mb-4" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login} className="bg-indigo-600 text-white px-4 py-2 rounded mr-2">Login</button><button onClick={register} className="border px-4 py-2 rounded">Registrieren</button>{err&&<p className="text-red-600 mt-3 text-sm">{err}</p>}</div></div>}
function Shell(){const nav=useNavigate();return <div><aside className="no-print fixed left-0 top-0 bottom-0 w-64 bg-slate-950 text-white p-5"><h2 className="font-bold text-xl mb-8">WorksheetAI</h2><nav className="space-y-3"><Link className="block" to="/app">Arbeitsblatt erstellen</Link><Link className="block" to="/app/worksheets">Meine Arbeitsblätter</Link><Link className="block" to="/app/patterns">Vorlagen</Link></nav><button className="mt-8 text-sm underline" onClick={()=>{localStorage.removeItem('access');nav('/login')}}>Logout</button></aside><main className="ml-64 p-6 print:ml-0 print:min-h-0 print:p-0 print:max-w-none"><Routes><Route index element={<GeneratorPage/>}/><Route path="worksheets" element={<MyWorksheetsPage/>}/><Route path="worksheets/:id" element={<WorksheetPage/>}/><Route path="patterns" element={<PatternPage/>}/></Routes></main></div>}
const loginDisabled=import.meta.env.VITE_DISABLE_LOGIN==='true';
function Protected(){if(loginDisabled)return <Shell/>;return localStorage.getItem('access')?<Shell/>:<Navigate to="/login"/>}
export default function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/app/*" element={<Protected/>}/><Route path="*" element={<Navigate to="/app"/>}/></Routes>}
