# Generated by Django 5.2.13 on 2026-05-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='generation_meta',
            field=models.JSONField(default=dict),
        ),
    ]
