# Generated by Django 5.2.13 on 2026-05-07 09:48

from django.db import migrations, models


def forwards_worksheet_moderation(apps, schema_editor):
    Worksheet = apps.get_model('worksheets', 'Worksheet')
    Worksheet.objects.filter(library_public=True).update(library_moderation_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0003_worksheet_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='library_moderation_status',
            field=models.CharField(choices=[('none', 'Nicht eingereicht'), ('pending', 'Freigabe ausstehend'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], db_index=True, default='none', max_length=20),
        ),
        migrations.RunPython(forwards_worksheet_moderation, migrations.RunPython.noop),
    ]
