# Generated by Django 5.2.13 on 2026-05-09 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0005_worksheet_library_listing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorksheetRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(blank=True)),
                ('revision_mode', models.CharField(choices=[('general', 'Allgemein'), ('bug_fix', 'Fehler beheben'), ('design_improve', 'Design verbessern'), ('touch_optimize', 'Touch optimieren'), ('content_change', 'Inhalt ändern'), ('simplify', 'Vereinfachen'), ('make_more_creative', 'Kreativer machen'), ('performance_improve', 'Performance verbessern')], default='general', max_length=30)),
                ('previous_content', models.JSONField(default=dict)),
                ('new_content', models.JSONField(default=dict)),
                ('previous_render_model', models.JSONField(default=dict)),
                ('new_render_model', models.JSONField(default=dict)),
                ('previous_metadata', models.JSONField(default=dict)),
                ('new_metadata', models.JSONField(default=dict)),
                ('ai_raw_output', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(default=list)),
                ('validation_warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet_revisions', to=settings.AUTH_USER_MODEL)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='worksheets.worksheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
