# Generated by Django 5.2.13 on 2026-05-13 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0006_worksheet_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='source_worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_worksheets', to='worksheets.worksheet'),
        ),
        migrations.CreateModel(
            name='WorksheetLibraryComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_library_comments', to=settings.AUTH_USER_MODEL)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_comments', to='worksheets.worksheet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['worksheet', '-created_at'], name='worksheets__workshe_1ea74a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorksheetRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_ratings', to=settings.AUTH_USER_MODEL)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='worksheets.worksheet')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('worksheet', 'user'), name='worksheet_rating_worksheet_user_uniq')],
            },
        ),
    ]
