# Generated by Django

import copy

from django.db import migrations, models
from django.utils import timezone as django_timezone


def forwards_backfill_snapshots(apps, schema_editor):
    Worksheet = apps.get_model('worksheets', 'Worksheet')
    for ws in Worksheet.objects.filter(library_public=True, library_moderation_status='approved'):
        ws.library_snapshot_content = copy.deepcopy(ws.content) if isinstance(ws.content, dict) else {}
        ws.library_snapshot_render_model = (
            copy.deepcopy(ws.render_model) if isinstance(ws.render_model, dict) else {}
        )
        ws.library_snapshot_page_setup = copy.deepcopy(ws.page_setup) if isinstance(ws.page_setup, dict) else {}
        ws.library_snapshot_generation_meta = (
            copy.deepcopy(ws.generation_meta) if isinstance(ws.generation_meta, dict) else {}
        )
        ws.library_snapshot_subject = ws.subject or ''
        ws.library_snapshot_grade = ws.grade
        ws.library_snapshot_topic = ws.topic or ''
        ws.library_snapshot_at = ws.library_published_at or django_timezone.now()
        ws.save(
            update_fields=[
                'library_snapshot_at',
                'library_snapshot_content',
                'library_snapshot_render_model',
                'library_snapshot_page_setup',
                'library_snapshot_generation_meta',
                'library_snapshot_subject',
                'library_snapshot_grade',
                'library_snapshot_topic',
            ],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0008_worksheetfolder_worksheet_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_render_model',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_page_setup',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_generation_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_subject',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='library_snapshot_topic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(forwards_backfill_snapshots, migrations.RunPython.noop),
    ]
